# app/utils/error_codes.py

ERROR_CODES = {
    "INVALID_CONTENT_TYPE": "INVALID_CONTENT_TYPE",
    "VALIDATION_ERROR": "VALIDATION_ERROR",
    "NOT_FOUND": "NOT_FOUND",
    "FORBIDDEN": "FORBIDDEN",
    "SERVER_ERROR": "SERVER_ERROR",
}

HTTP_STATUS_TO_ERROR_CODE = {
    400: ERROR_CODES["VALIDATION_ERROR"],
    401: ERROR_CODES["FORBIDDEN"],
    403: ERROR_CODES["FORBIDDEN"],
    404: ERROR_CODES["NOT_FOUND"],
    415: ERROR_CODES["INVALID_CONTENT_TYPE"],
    500: ERROR_CODES["SERVER_ERROR"],
}
