# app/utils/error_codes.py

ERROR_CODES = {
    "INVALID_CONTENT_TYPE": "INVALID_CONTENT_TYPE",
    "VALIDATION_ERROR": "VALIDATION_ERROR",
    "NOT_FOUND": "NOT_FOUND",
    "FORBIDDEN": "FORBIDDEN",
    "SERVER_ERROR": "SERVER_ERROR",
    "TOO_MANY_REQUESTS": "TOO_MANY_REQUESTS",
    "INVALID_TOKEN": "INVALID_TOKEN",
    "DUPLICATE_TRANSACTION": "DUPLICATE_TRANSACTION",
}


HTTP_STATUS_TO_ERROR_CODE = {
    400: ERROR_CODES["VALIDATION_ERROR"],
    401: ERROR_CODES["FORBIDDEN"],
    403: ERROR_CODES["FORBIDDEN"],
    404: ERROR_CODES["NOT_FOUND"],
    415: ERROR_CODES["INVALID_CONTENT_TYPE"],
    429: ERROR_CODES["TOO_MANY_REQUESTS"],
    500: ERROR_CODES["SERVER_ERROR"],
}
